In [1]:
import tensorflow as tf

In [11]:
# import image files from external folders
dataset = tf.data.Dataset.list_files('images/*/*', shuffle=False) #! asterisk * means wildcard
dataset # what inside this dataset is just image paths, the images have not yet been read.
for elem in dataset.take(10):
    print(elem.numpy()) # print out the 10 paths of the images

b'images/cat/20 Reasons Why Cats Make the Best Pets....jpg'
b'images/cat/7 Foods Your Cat Can_t Eat.jpg'
b'images/cat/A cat appears to have caught the....jpg'
b'images/cat/Adopt-A-Cat Month\xc2\xae - American Humane....jpg'
b'images/cat/All About Your Cat_s Tongue.jpg'
b'images/cat/Alley Cat Allies _ An Advocacy....jpg'
b'images/cat/Are Cats Domesticated_ _ The New Yorker.jpg'
b'images/cat/Cat Advice _ Collecting a Urine Sample....jpg'
b'images/cat/Cat Throwing Up_ Normal or Cause for....jpg'
b'images/cat/Cat intelligence - Wikipedia.jpg'


In [12]:
# import image files from external folders with shuffle being true
dataset = tf.data.Dataset.list_files('images/*/*', shuffle=True) #! asterisk * means wildcard
dataset # what inside this dataset is just image paths, the images have not yet been read.
for elem in dataset.take(10):
    print(elem.numpy()) # print out the 10 paths of the images with shuffled order 

b'images/dog/The Black Dog Tavern Company _ Life off....jpg'
b'images/dog/Common Dog Breeds and Their Health Issues.jpg'
b'images/dog/How to make your dog feel comfortable....jpg'
b'images/cat/International Cat Care _ The ultimate....jpg'
b'images/dog/7 Tips on Canine Body Language _ ASPCApro.jpg'
b'images/dog/List of Dog Breeds _ Petfinder.jpg'
b'images/dog/Cats and Dogs.jpg'
b'images/cat/The Science-Backed Benefits of Being a....jpg'
b'images/dog/Welcoming Your Adopted Dog Into Your....jpg'
b'images/dog/dog existed at the end of the Ice Age_yythkg....jpg'


In [13]:
# Now the objectives are as follows
# 1: split dataset into training dataset and test dataset with 8:2 ratio
# 2: capture the label from the path of the image
# 3: import image data and decode from jpeg to array tensor
# 4: scaling the data
# 5: batch the dataset 

In [24]:
# 1: split dataset into training dataset and test dataset with 8:2 ratio
image_num = len(list(dataset)) #HACK: First convert DatasetV1Adapter to list before using len() 
image_num

130

In [32]:
train_num = int(image_num * 0.8)
train_ds = dataset.take(train_num)
test_ds = dataset.skip(train_num)

In [45]:
import os
os.path.sep

'/'

In [51]:
# 2: capture the label from the path of the image

def get_label(elem):
    return elem.split('/') #! This function can't be applied to tensor type data directly

def get_label_tf(elem):
    return tf.strings.split(elem, os.path.sep)[-2]

In [53]:
for elem in dataset.take(3):
    label = get_label_tf(elem) # apply the defined function to every element in dataset
    print(label.numpy()) 

b'cat'
b'dog'
b'dog'


In [59]:
# The following function read images and resize it while invoking get_label_tf() function
def pre_process(elem):
    label = get_label_tf(elem)
    imag = tf.io.read_file(elem) 
    imag = tf.image.decode_jpeg(imag)
    imag = tf.image.resize(imag,[128,128]) # resize the first two dimension size 
    return imag, label

def scaling(elem):
    return elem/255

(128, 128, 3)
(128, 128, 3)
(128, 128, 4)
(128, 128, 3)
(128, 128, 3)


In [65]:
# for elem in train_ds.take(5):
#     imag, label = pre_process(elem)
#     print(imag.numpy().shape)

# use map() method to apply the pre_process function to all the elements in the dataset    
for img, label in train_ds.map(pre_process).take(1): 
    print(imag.numpy())
    print(label.numpy())


[[[6.54062500e+01 8.14062500e+01 1.07406250e+02]
  [6.86093750e+01 8.46093750e+01 1.10609375e+02]
  [7.17968750e+01 8.77968750e+01 1.13796875e+02]
  ...
  [5.06093750e+01 7.06093750e+01 9.56093750e+01]
  [4.90317383e+01 6.90317383e+01 9.40317383e+01]
  [4.65053711e+01 6.65053711e+01 9.15053711e+01]]

 [[6.64379883e+01 8.34379883e+01 1.09437988e+02]
  [6.56093750e+01 8.26093750e+01 1.08609375e+02]
  [6.44062500e+01 8.14062500e+01 1.07406250e+02]
  ...
  [5.60864258e+01 7.60864258e+01 1.01086426e+02]
  [5.16093750e+01 7.16093750e+01 9.66093750e+01]
  [6.22968750e+01 7.92968750e+01 1.05296875e+02]]

 [[6.12812500e+01 8.32812500e+01 1.07281250e+02]
  [6.30131836e+01 8.50131836e+01 1.09013184e+02]
  [6.11782227e+01 8.31782227e+01 1.07178223e+02]
  ...
  [5.16093750e+01 7.16093750e+01 9.66093750e+01]
  [5.66562500e+01 7.66562500e+01 1.01656250e+02]
  [7.42856445e+01 8.82856445e+01 1.15285645e+02]]

 ...

 [[1.28564453e+00 1.28564453e+00 1.28564453e+00]
  [1.16943359e+00 1.16943359e+00 1.1694

In [ ]:
train_ds = train_ds.map(pre_process) # update train_ds dateset

In [74]:
for img, label in train_ds.take(10):
    # print(img)
    print(label)

tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)


In [77]:
dataset1 = tf.data.Dataset.range(100)
for i in dataset1:
    print(i)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(10, shape=(), dtype=int64)
tf.Tensor(11, shape=(), dtype=int64)
tf.Tensor(12, shape=(), dtype=int64)
tf.Tensor(13, shape=(), dtype=int64)
tf.Tensor(14, shape=(), dtype=int64)
tf.Tensor(15, shape=(), dtype=int64)
tf.Tensor(16, shape=(), dtype=int64)
tf.Tensor(17, shape=(), dtype=int64)
tf.Tensor(18, shape=(), dtype=int64)
tf.Tensor(19, shape=(), dtype=int64)
tf.Tensor(20, shape=(), dtype=int64)
tf.Tensor(21, shape=(), dtype=int64)
tf.Tensor(22, shape=(), dtype=int64)
tf.Tensor(23, shape=(), dtype=int64)
tf.Tensor(24, shape=(), dtype=int64)
tf.Tensor(25, shape=(), dtype=int64)
tf.Tensor(26, shape=(), dtype=int64)
tf.Tensor(2

In [79]:
dataset2 = tf.data.Dataset.range(0,-100,-1)
for i in dataset2:
    print(i)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(-1, shape=(), dtype=int64)
tf.Tensor(-2, shape=(), dtype=int64)
tf.Tensor(-3, shape=(), dtype=int64)
tf.Tensor(-4, shape=(), dtype=int64)
tf.Tensor(-5, shape=(), dtype=int64)
tf.Tensor(-6, shape=(), dtype=int64)
tf.Tensor(-7, shape=(), dtype=int64)
tf.Tensor(-8, shape=(), dtype=int64)
tf.Tensor(-9, shape=(), dtype=int64)
tf.Tensor(-10, shape=(), dtype=int64)
tf.Tensor(-11, shape=(), dtype=int64)
tf.Tensor(-12, shape=(), dtype=int64)
tf.Tensor(-13, shape=(), dtype=int64)
tf.Tensor(-14, shape=(), dtype=int64)
tf.Tensor(-15, shape=(), dtype=int64)
tf.Tensor(-16, shape=(), dtype=int64)
tf.Tensor(-17, shape=(), dtype=int64)
tf.Tensor(-18, shape=(), dtype=int64)
tf.Tensor(-19, shape=(), dtype=int64)
tf.Tensor(-20, shape=(), dtype=int64)
tf.Tensor(-21, shape=(), dtype=int64)
tf.Tensor(-22, shape=(), dtype=int64)
tf.Tensor(-23, shape=(), dtype=int64)
tf.Tensor(-24, shape=(), dtype=int64)
tf.Tensor(-25, shape=(), dtype=int64)
tf.Tensor(-26, shape=()

In [83]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2)) #NOTE: zip() method combines two elements into a tuple! 
for i, j in dataset3.take(10):
    print(i)
    print(j)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(-1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(-2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(-3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(-4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(-5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(-6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(-7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(-8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(-9, shape=(), dtype=int64)


In [90]:
dataset4 = dataset3.batch(3) # each element inside dataset4 is in form of ([-1,-2,-3] [0,-1,-2])
for batch in dataset4.take(10):
    print([arry.numpy() for arry in batch])
dataset4

[array([0, 1, 2]), array([ 0, -1, -2])]
[array([3, 4, 5]), array([-3, -4, -5])]
[array([6, 7, 8]), array([-6, -7, -8])]
[array([ 9, 10, 11]), array([ -9, -10, -11])]
[array([12, 13, 14]), array([-12, -13, -14])]
[array([15, 16, 17]), array([-15, -16, -17])]
[array([18, 19, 20]), array([-18, -19, -20])]
[array([21, 22, 23]), array([-21, -22, -23])]
[array([24, 25, 26]), array([-24, -25, -26])]
[array([27, 28, 29]), array([-27, -28, -29])]


<BatchDataset shapes: ((None,), (None,)), types: (tf.int64, tf.int64)>

In [92]:
# Since the last batch may not be full, we can use
# drop_remainder argument to ignore the last batch 
dataset5 = dataset3.batch(7,drop_remainder=True)
dataset5

<BatchDataset shapes: ((7,), (7,)), types: (tf.int64, tf.int64)>

In [104]:
## Batching tensors with padding
# When a model work with input data varying in size, we may need to pad the data.
dataset = tf.data.Dataset.range(100)
for i in dataset.take(10):
    print(i.numpy())

0
1
2
3
4
5
6
7
8
9


In [129]:
tf.fill([3],5)

<tf.Tensor: id=13159, shape=(3,), dtype=int32, numpy=array([5, 5, 5], dtype=int32)>

In [133]:
dataset_ = dataset.map(lambda x: tf.fill([tf.cast(x, tf.int32)], x)) #NOTE: tf.fill() creates a tensor filled with a scalar value
for i in dataset_.take(10):               # NOTE: Inside the fill(), the dimension has to be in brackets, x is the value to fill the tensor
    print(i)

tf.Tensor([], shape=(0,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2 2], shape=(2,), dtype=int64)
tf.Tensor([3 3 3], shape=(3,), dtype=int64)
tf.Tensor([4 4 4 4], shape=(4,), dtype=int64)
tf.Tensor([5 5 5 5 5], shape=(5,), dtype=int64)
tf.Tensor([6 6 6 6 6 6], shape=(6,), dtype=int64)
tf.Tensor([7 7 7 7 7 7 7], shape=(7,), dtype=int64)
tf.Tensor([8 8 8 8 8 8 8 8], shape=(8,), dtype=int64)
tf.Tensor([9 9 9 9 9 9 9 9 9], shape=(9,), dtype=int64)


In [140]:
# Now we need to pad the above tensors
dataset_pad = dataset_.padded_batch(7, padded_shapes=(None,)).take(3) # Each batch has four elements, and the shorter elements are padded with zeros.
for i in dataset_pad:
    print(i.numpy())

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [2 2 0 0 0 0]
 [3 3 3 0 0 0]
 [4 4 4 4 0 0]
 [5 5 5 5 5 0]
 [6 6 6 6 6 6]]
[[ 7  7  7  7  7  7  7  0  0  0  0  0  0]
 [ 8  8  8  8  8  8  8  8  0  0  0  0  0]
 [ 9  9  9  9  9  9  9  9  9  0  0  0  0]
 [10 10 10 10 10 10 10 10 10 10  0  0  0]
 [11 11 11 11 11 11 11 11 11 11 11  0  0]
 [12 12 12 12 12 12 12 12 12 12 12 12  0]
 [13 13 13 13 13 13 13 13 13 13 13 13 13]]
[[14 14 14 14 14 14 14 14 14 14 14 14 14 14  0  0  0  0  0  0]
 [15 15 15 15 15 15 15 15 15 15 15 15 15 15 15  0  0  0  0  0]
 [16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16  0  0  0  0]
 [17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17  0  0  0]
 [18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18  0  0]
 [19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19  0]
 [20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20]]


In [149]:
# two tensors can be combined into one dataset object.
features = tf.constant([[1,3],[2,1],[3,3]]) # 3 x 2 tensor
labels = tf.constant(['A','B','A']) # 3 x 1 tensos.
dataset = tf.data.Dataset.from_tensor_slices((features,labels)) 
dataset # we can see the shape that the first dimension 3 is being removed and only the second dimension 2 left in the first tensor. 
# The second tensor becomes () because the second dimension of the second tensor is 1.

<TensorSliceDataset shapes: ((2,), ()), types: (tf.int32, tf.string)>

In [150]:
for elem in dataset.as_numpy_iterator():
    print(elem)

AttributeError: 'TensorSliceDataset' object has no attribute 'as_numpy_iterator'